spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

user:
  age: 18

